apiVersion: v1
kind: List
items:
- apiVersion: batch/v1
  kind: Job
  metadata:
    labels:
      job-name: openshift-ansible-istio-job
    name: openshift-ansible-istio-job
    namespace: istio-system
  spec:
    activeDeadlineSeconds: 300
    backoffLimit: 6
    completions: 1
    parallelism: 1
    template:
      metadata:
        labels:
          job-name: openshift-ansible-istio-job
      spec:
        containers:
        - env:
          - name: INVENTORY_FILE
            value: /tmp/inventory
          - name: PLAYBOOK_FILE
            value: playbooks/openshift-istio/config.yml
          - name: OPTS
            value: -vvv
          image: openshiftistio/origin-ansible:0.7.1
          imagePullPolicy: IfNotPresent
          name: openshift-ansible-istio-job
          securityContext:
            runAsUser: 0
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /etc/origin/master
            name: configdir
          - mountPath: /tmp/inventory
            name: inventoryfile
        dnsPolicy: ClusterFirst
        hostNetwork: true
        restartPolicy: Never
        schedulerName: default-scheduler
        serviceAccount: openshift-ansible
        serviceAccountName: openshift-ansible
        terminationGracePeriodSeconds: 30
        volumes:
        - hostPath:
            path: /etc/origin/master
          name: configdir
        - hostPath:
            path: /var/lib/origin/openshift.local.config/istio.inventory
          name: inventoryfile
