apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  name: istio-elasticsearch-sysctl
  labels:
    machineconfiguration.openshift.io/role: worker
spec:
  config:
    ignition:
      config: {}
      security:
        tls: {}
      timeouts: {}
      version: 2.2.0
    storage:
      files:
        - contents:
            source: >-
              data:text/plain;charset=utf-8,vm.max_map_count%20%3D%20262144
            verification: {}
          filesystem: root
          mode: 444
          path: /etc/sysctl.d/99-elasticsearch.conf
